routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/table', function () {
    return view('includes.content_table');
});
Route::get('/data-table', function () {
    return view('includes.content_data_table');
});
//MANUAL
// Route::get('/cast/create','CastController@create');
// Route::post('/cast','CastController@store');
// Route::get('/cast','CastController@index')->name('post.index');
// Route::get('/cast/{cast_id}','CastController@detail');
// Route::get('/cast/{id}/edit','CastController@edit');
// Route::put('/cast/{id}','CastController@update');
// Route::delete('/cast/{id}','CastController@delate');

//RESOURCE
// Route::resource('casting','CastingController');
Route::resource('cast','CastController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/cast.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class cast extends Model
{
    protected $table="cast";
    protected $fillable=["nama","umur","bio"];
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\cast;
class CastController extends Controller
{
    public function create(){
        return view('post.create');
    }
    public function store(Request $request){
        $request->validate([
            'nama'=>'required|unique:cast',
            'bio'=>'required',
            'umur'=>'required'
        ]);
        //BIASA
        // $query=DB::table('cast')->insert(
        //     [
        //         "nama"=>$request['nama'],
        //         "umur"=>$request['umur'],
        //         "bio"=>$request['bio']
        //     ]
        // );

        //ORM
        // $cast=new cast;
        // $cast->nama= $request['nama'];
        // $cast->umur=$request['umur'];
        // $cast->bio=$request['bio'];
        // $cast->save();

        //MASS ASSIGMENT
        $cast=cast::create([
            "nama"=>$request["nama"],
            "umur"=>$request["umur"],
            "bio"=>$request["bio"]
        ]);
        return redirect('/cast')->with('sukses','Yee selamat data Berhasil Disimpan');
    }
    public function index(){
        //query builder
        // $cast=DB::table('cast')->get();

        //ORM
        $cast=cast::all(); 
        return view('post.index',compact('cast'));
    }
    public function show($id){
        //query BUilder
        // $cast=DB::table('cast')->where('id',$id)->first();
        
        //ORM
        $cast=cast::find($id);
        return view('post.detail',compact('cast'));
    }
    public function edit($id){
        //QUERY BUILDER
        // $cast=DB::table('cast')->where('id',$id)->first();
        
        //ORM
        $cast=cast::find($id);
        return view('post.edit',compact('cast'));
    }
    public function update($id,Request $request){
        $request->validate([
            'nama'=>'required',
            'bio'=>'required',
            'umur'=>'required'
        ]);
        //QUERY BUILDER
        // $query=DB::table('cast')->where('id',$id)->update([
        //     "nama"=>$request['nama'],
        //     "umur"=>$request['umur'],
        //     "bio"=>$request['bio']
        // ]);
        
        //ORM
        $update=cast::where('id',$id)->update([
            "nama"=>$request['nama'],
            "umur"=>$request['umur'],
            "bio"=>$request['bio']
        ]);
        return redirect('/cast')->with('sukses','Yee selamat data Berhasil Diupdate');
    }
    public function destroy($id){
        //QUERY BUILDR
        // $query=DB::table('cast')->where('id',$id)->delete();

        //ORM
        cast::destroy($id);
        return redirect('/cast')->with('sukses','Data Anda Berhasil Dihapus');
    }
}

app/Http/Controllers/CastingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CastingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/include/footer.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.1.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

resources/views/include/head.blade.php
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Simple Tables</title>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('/plugins/fontawesome-free/css/all.min.css')}} ">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset ('/dist/css/adminlte.min.css')}}">
</head>

resources/views/include/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button">
            <i class="fas fa-bars"></i>
        </a>
        </li>
    </ul>
</nav>

resources/views/include/script.blade.php
<!-- jQuery -->
<script src="{{asset ('/plugins/jquery/jquery.min.js')}}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{asset('/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{asset ('/dist/js/adminlte.min.js')}}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{asset ('/dist/js/demo.js')}}"></script>

    @stack('script')

resources/views/include/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
        <img src="{{asset ('/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset ('/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Alexander Pierce</a>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                    with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                </li>
                <li class="nav-item menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-table"></i>
                        <p>
                            Tables
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/post/create.blade.php
@extends('welcome')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Tambah Data</h1>
                </div>
                <!-- /.col -->
                <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#">Cast</a>
                    </li>
                    <li class="breadcrumb-item active">Tambah Cast</li>
                </ol>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <!-- column -->
            <div class="col-sm-12">
                <div class="card">
                    <div class="row">
                        <!-- column -->
                        <div class="col-sm-12">
                            <div class="card-body">
                                <section class="content">
                                    <div class="card card-info">
                                        <div class="card-header">
                                            <h3 class="card-title" style="margin-top:5px;">
                                                <i class="far fa-list-alt"></i> Form Tambah Cast
                                            </h3>
                                        </div>
                                        <!-- /.card-header -->
                                        <!-- form start -->
                                        <br>
                                        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="/cast">
                                            @csrf
                                            <div class="card-body">
                                                <div class="form-group row">
                                                    <label for="nama" class="col-sm-3 col-form-label">Nama </label>
                                                    <div class="col-sm-7">
                                                        <input type="text" name="nama" class="form-control" id="nama" value="{{ old('nama','') }}">
                                                        @error('nama')
                                                            <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="umur" class="col-sm-3 col-form-label">Umur</label>
                                                    <div class="col-sm-7">
                                                        <input type="number" name="umur" class="form-control" id="umur" value="{{old('umur','')}}">
                                                        @error('umur')
                                                            <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="bio" class="col-sm-3 col-form-label">Bio</label>
                                                    <div class="col-sm-7">
                                                        <input type="text" name="bio" class="form-control" id="bio" value="{{old('bio','')}}">
                                                        @error('bio')
                                                            <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- /.card-body -->
                                            <div class="card-footer">
                                                <button type="submit" class="btn btn-info float-right" name="submit">
                                                    <i class="mr-3 fas fa-plus" aria-hidden="true"></i>Tambah
                                                </button>
                                                <div class="text-left upgrade-btn">
                                                    <a href="{{route('cast.index')}}" class="btn btn-sm btn-warning d-none d-md-inline-block text-white">
                                                        <i class="mr-3  fas fa-arrow-left" aria-hidden="true"></i>
                                                        Kembali
                                                    </a>
                                                </div>
                                            </div>
                                            <!-- /.card-footer -->
                                        </form>
                                    </div>
                                    <!-- /.card -->
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content -->
@endsection

resources/views/post/edit.blade.php
@extends('welcome')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Edit Data</h1>
                </div>
                <!-- /.col -->
                <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="/cast">Cast</a>
                    </li>
                    <li class="breadcrumb-item active">Edit Cast</li>
                </ol>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <!-- column -->
            <div class="col-sm-12">
                <div class="card">
                    <div class="row">
                        <!-- column -->
                        <div class="col-sm-12">
                            <div class="card-body">
                                <section class="content">
                                    <div class="card card-info">
                                        <div class="card-header">
                                            <h3 class="card-title" style="margin-top:5px;">
                                                <i class="far fa-list-alt"></i> Form Edit Cast
                                            </h3>
                                        </div>
                                        <!-- /.card-header -->
                                        <!-- form start -->
                                        <br>
                                        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="/cast/{{$cast->id}}">
                                            @csrf
                                            @method('PUT')
                                            <div class="card-body">
                                                <div class="form-group row">
                                                    <label for="nama" class="col-sm-3 col-form-label">Nama </label>
                                                    <div class="col-sm-7">
                                                        <input type="text" name="nama" class="form-control" id="nama" value="{{ old('nama',$cast->nama) }}">
                                                        @error('nama')
                                                            <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="umur" class="col-sm-3 col-form-label">Umur</label>
                                                    <div class="col-sm-7">
                                                        <input type="number" name="umur" class="form-control" id="umur" value="{{old('umur',$cast->umur)}}">
                                                        @error('umur')
                                                            <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="bio" class="col-sm-3 col-form-label">Bio</label>
                                                    <div class="col-sm-7">
                                                        <input type="text" name="bio" class="form-control" id="bio" value="{{old('bio',$cast->bio)}}">
                                                        @error('bio')
                                                            <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- /.card-body -->
                                            <div class="card-footer">
                                                <button type="submit" class="btn btn-info float-right" name="submit">
                                                    <i class="mr-3 fas fa-plus" aria-hidden="true"></i>Edit
                                                </button>
                                                <div class="text-left upgrade-btn">
                                                    <a href="{{route('cast.index')}}" class="btn btn-sm btn-warning d-none d-md-inline-block text-white">
                                                        <i class="mr-3  fas fa-arrow-left" aria-hidden="true"></i>
                                                        Kembali
                                                    </a>
                                                </div>
                                            </div>
                                            <!-- /.card-footer -->
                                        </form>
                                    </div>
                                    <!-- /.card -->
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content -->
@endsection

resources/views/post/index.blade.php
@extends('welcome')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Data Cast</h1>
                </div>
                <!-- /.col -->
                <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="index.php">Home</a>
                    </li>
                    <li class="breadcrumb-item active">Cast</li>
                </ol>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <!-- column -->
            <div class="col-sm-12">
                <div class="card">
                    <div class="row">
                        <!-- column -->
                        <div class="col-sm-12">
                            <div class="card-body">
                                <div class="card-header">
                                    <h3 class="card-title" style="margin-top:5px;">
                                        <i class="mr-3 far fa-building"aria-hidden="true"></i> Daftar Cast
                                    </h3>
                                    <div class="card-tools">
                                        <a href="{{route('cast.create')}}" class="btn btn-sm btn-info float-right">
                                            <i class="fas fa-plus"></i> Tambah Daftar Cast
                                        </a>
                                    </div>
                                </div> 
                                <div class="card-body">
                                    <div class="col-md-12">
                                        <form method="post" action="">
                                            <div class="row">
                                                <div class="col-md-4 bottom-10">
                                                    <input type="text" class="form-control" id="kata_kunci" name="katakunci" placeholder="Cari Nama Cabang">
                                                </div>
                                                <div class="col-md-5 bottom-10">
                                                    <button type="submit" class="btn btn-primary">
                                                        <i class="mr-3 fas fa-search"aria-hidden="true"></i>&nbsp; Search
                                                    </button>
                                                </div>
                                            </div>
                                            <!-- .row -->
                                        </form>
                                    </div>
                                    <br>
                                    @if(session('sukses'))
                                        <div class="col-sm-12">
                                            <div class="alert alert-success">
                                                {{session('sukses')}}
                                            </div>
                                        </div>
                                    @endif
                                    <table class="table table-bordered">
                                        <thead>                  
                                            <tr>
                                                <th width="5%">NO</th>
                                                <th width="15%">Nama</th>
                                                <th width="15%">Umur</th>
                                                <th width="15%">Bio</th>
                                                <th width="20%">
                                                    <center>Aksi</center>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>	
                                            @forelse($cast as $key=>$casts)
                                                <tr>
                                                    <td>{{$key+1}}</td>
                                                    <td>{{$casts->nama}}</td>
                                                    <td>{{$casts->umur}}</td>
                                                    <td>{{$casts->bio}}</td>
                                                    <td align="center">
                                                        <a href="{{route('cast.edit',['cast'=>$casts->id],'edit')}}" class="btn btn-xs btn-info">
                                                            <i class="fas fa-edit"></i> Edit
                                                        </a>
                                                        <form action="{{route('cast.destroy',['cast'=>$casts->id])}}" method="post">
                                                            @csrf
                                                            @method('DELETE')
                                                            <input type="submit" value="delete" class="btn btn-xs btn-warning">
                                                        </form> 
                                                        <a href="{{route('cast.show',['cast'=>$casts->id])}}" class="btn btn-xs bg-success" title="Detail">
                                                            <i class="fas fa-eye"></i>  Detail 
                                                        </a> 
                                                    </td>
                                                </tr>
                                                @empty
                                                <tr>
                                                    <td colspan="5" align="center">No Post</td>
                                                </tr>
                                            @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content -->
@endsection